### ISSUE TITLE
Use of fixedCodeableConcept in Consent profile

### ISSUE THREAD

**Issue by richardtownleyoneill-ADHA** [AuDigitalHealth/ci-medicare-records#2]
# Prerequisites

- [x ] I have verified the problem exists in the available content
- [ x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ x] I have written a descriptive issue title

# The bug
Consent Australian Organ Donor Register profile sets the value on `Consent.category:organDonationConsent` and `Consent.except.action` using fixedCodeableConcept. Fixing the value in this way prohibits parts of CodeableConcept that are intended to be optional including CodeableConcept.text and CodeableConcept.coding.display.

## What I expected to happen
* I suggest using patternCodeableConcept in place of fixedValueCodeableConcept

## Steps to reproduce
This is visible in the snapshot display in the IG. The lines in the structure definitions can be found by finding "fixedCodeableConcept"

**Comment by dtr-agency** [comment]
Consent.category:organDonationConsent fixed via https://github.com/AuDigitalHealth/ci-medicare-records/issues/6
