### ISSUE TITLE
Remove referral support - not supplied by Services Australia

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-medicare-records#21]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
Advice provided from NIO that Service Requestor from Services Australia for MBS has never been received in the past, and is not part of the live feed design.

**Impact to design**
[ADHA Medicare ExplanationOfBenefit](https://build.fhir.org/ig/AuDigitalHealth/ci-medicare-records/StructureDefinition-explanationofbenefit-medicare.html) ExplanationOfBenefit.referral is not to be supported and the [ADHA MBS DVA ReferralRequest](https://build.fhir.org/ig/AuDigitalHealth/ci-medicare-records/StructureDefinition-referralrequest-mbsdva.html) profile governing that element is not required.

**Actions**

1. Update [ADHA Medicare ExplanationOfBenefit](https://build.fhir.org/ig/AuDigitalHealth/ci-medicare-records/StructureDefinition-explanationofbenefit-medicare.html) to remove any differential of ExplanationOfBenefit.referral
2. [ADHA MBS DVA ReferralRequest](https://build.fhir.org/ig/AuDigitalHealth/ci-medicare-records/StructureDefinition-referralrequest-mbsdva.html) is to be archived.

**Comment by dtr-agency** [comment]
In review and testing with @dbojicic-agency via https://jira.digitalhealth.gov.au/browse/AN-470.

**Comment by dbojicic-agency** [comment]
Review and testing completed with no issues found.
