### ISSUE TITLE
ConsentDonationDecision :: StructureDefinition.description needs an update

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-medicare-records#22]
# Prerequisites

- [X] I have verified the problem exists in the available content
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title

# The bug
StructureDefinition.description should be updated to include the text 'used to represent' instead of 'represents'.

The same fix to be applied to intro.md.

**Comment by dtr-agency** [comment]
In review and testing with @dbojicic-agency via https://jira.digitalhealth.gov.au/browse/AN-470.

**Comment by dbojicic-agency** [comment]
Review and testing completed with no issues found.
