### ISSUE TITLE
Remove Date of Initial Registration from AODR - not supplied by Services Australia

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-medicare-records#23]
# Prerequisites

- [X] I have verified the problem exists in the available content
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title

# The issue / feature
Advice provided from NIO that Date of Initial Registration from Services Australia for AODR is not part of the Live Feed.

**Impact to design**
[ADHA Australian Organ Donor Register Consent](https://build.fhir.org/ig/AuDigitalHealth/ci-medicare-records/StructureDefinition-consent-aodr.html) Consent.dateInitialRegistration is not to be supported and the [Date of Initial Registration](https://build.fhir.org/ig/AuDigitalHealth/ci-medicare-records/StructureDefinition-extension-dateinitialregistration.html) extension structure is not required.

**Actions**

1. Update [ADHA Australian Organ Donor Register Consent](https://build.fhir.org/ig/AuDigitalHealth/ci-medicare-records/StructureDefinition-consent-aodr.html) to remove any differential of Consent.dateInitialRegistration
2. [Date of Initial Registration](https://build.fhir.org/ig/AuDigitalHealth/ci-medicare-records/StructureDefinition-extension-dateinitialregistration.html) is to be archived.

**Comment by dtr-agency** [comment]
In review and testing with @dbojicic-agency via https://jira.digitalhealth.gov.au/browse/AN-470.

**Comment by dbojicic-agency** [comment]
Confirmed changes with no issues found.
