### ISSUE TITLE
Include practitioner-classification extension in MBS - supplied by Services Australia

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-medicare-records#24]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
Advice provided from NIO that [practitioner-classification](http://hl7.org/fhir/STU3/extension-practitioner-classification.html) extension is part of the live feed from Services Australia for MBS. 

**Impact to design**
The contained Practitioner resource referenced in ExplanationOfBenefit.provider governed by profile [ADHA Medicare ExplanationOfBenefit](https://build.fhir.org/ig/AuDigitalHealth/ci-medicare-records/StructureDefinition-explanationofbenefit-medicare.html) is to support the [practitioner-classification](http://hl7.org/fhir/STU3/extension-practitioner-classification.html) extension.

**Actions**

1. Update intro material on [ADHA Medicare ExplanationOfBenefit](https://build.fhir.org/ig/AuDigitalHealth/ci-medicare-records/StructureDefinition-explanationofbenefit-medicare.html) to include mention of the [practitioner-classification](http://hl7.org/fhir/STU3/extension-practitioner-classification.html) extension.

**Comment by dtr-agency** [comment]
In review and testing with @dbojicic-agency via https://jira.digitalhealth.gov.au/browse/AN-470.

**Comment by dbojicic-agency** [comment]
Review and testing completed with no issues found.
