### ISSUE TITLE
Incorrect use of contained resources in Explanation of Benefit Medicare

### ISSUE THREAD

**Issue by richardtownleyoneill-ADHA** [AuDigitalHealth/ci-medicare-records#3]
# Prerequisites
- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/AuDigitalHealth/ci-medicare-records/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/AuDigitalHealth/ci-medicare-records/issues?q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
In Explanation of Benefit Medicare the elements referral and prescription are required to refer to contained resources. 

This assertion was made due to a misunderstanding of contained resources and prevents using this resource as intended.

The most serious problem is that it is impossible to validly include a prescription in Explanation of Benefit Medicare. This is because the element prescription is a contained reference to Medication Request Pharmaceutical Benefits Scheme; it has a required element, medicationReference, which is also a contained reference,  and contained resources cannot be nested.

## What I expected to happen
Redesign with business owners a solution with less or no containment.
Relax requirements for containment.

## Workarounds
Do not validate against the profile.

**Comment by dtr-agency** [comment]
The solution is to remove the aggregation rule from Medication Request Pharmaceutical Benefits Scheme - Medication and MedicationRequest can be contained in the ExplanationOfBenefit resource.

Need to check however if the contained is forcing Medication to be contained in MedicationRequest or if a contained resource reference is sufficient where both resources MedicationRequest and Medication are contained in ExplanationOfBenefit.

**Comment by dtr-agency** [comment]
This is not an error, the behaviour is as desired, references are to contained resources - it does not force nested contains.
