### ISSUE TITLE
The package name should be in an Agency space

### ISSUE THREAD

**Issue by richardtownleyoneill-ADHA** [AuDigitalHealth/ci-medicare-records#8]
# Prerequisites

- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
The package name set in ig.json is in the HL7 AU name space: "npm-name": "hl7.fhir.au.dh.medicare-records".
This is only correct if this is an HL7 AU managed profile, which this is not.
The package name should be in a name space managed by the Agency.

## What I expected to happen
Use a new and appropriate package name

## Steps to reproduce
View https://github.com/AuDigitalHealth/ci-medicare-records/blob/master/ig.json

## Screenshots
N/A

## Workarounds
None

## QA.html excerpt

**Dependency Checks:**
<html>
<body>

Dependency Checks | Package | Version | FHIR Release | Canonical | Web Base | Comment
-- | -- | -- | -- | -- | -- | --
_ | hl7.fhir.au.dh.medicare-records | 2.0.1 | 3.0.2 | http://ns.electronichealth.net.au/ci/fhir |   |  
_ | hl7.fhir.au.base | 0.9.3 | 3.0.1 | http://hl7.org.au/fhir | http://hl7.org.au/fhir/2018Sep |  

</body>
</html>

## Desktop (please complete the following information):
- Date this bug was detected: 10/05/2021

**Comment by dtr-agency** [comment]
Agency package ids in space au.digitalhealth

This package id has been updated to be au.digitalhealth.stu3.medicare-records
