### ISSUE TITLE
Immunization Australian Immunisation Register - consider including major version number in the URL to manage breaking changes

### ISSUE THREAD

**Issue by dbojicic-agency** [AuDigitalHealth/ci-medicare-records#9]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
The Australian Immunisation Register Immunisation (StructureDefinition-immunization-air) profile has been updated in v2.1.0 of the implementation guide, including removing some of the unused version 1 and adding new functionality; subsequently the profile major version number increased. The profile URL has not changed between the versions. 

It is recommended (though not required) to include major version number in the canonical URL for a profile so that it can be referenced by its major version. Managing version dependencies can also be done by other methods (e.g. managing a set of resources with specific versioned references via an Implementation Guide). 

How would NIO & Services Australia like to manage breaking changes in the future?

## What it actually enables people to do
Allow a reference to a particular business version of the structure definition.

## Workarounds
N/A

## Additional context
N/A

**Comment by dtr-agency** [comment]
The content in this space is managed under different conventions. All profiles should be managed the same - only one profile for Flag has a version number in the URL which was introduced in the latest set. This should be reverted so that the content managed under this IG is all managed in the same way.
